

const FETH_GRID_SUCCESS   = 'FETH_GRID_SUCCESS'
const FETH_GRID_REQUEST   = 'FETH_GRID_REQUEST'
const FETH_GRID_FAILURE   = 'FETH_GRID_FAILURE'
const ON_MOVE_TO_LEFT     = 'ON_MOVE_TO_LEFT'
const ON_MOVE_TO_RIGHT    = 'ON_MOVE_TO_RIGHT'
const ON_MOVE             = 'ON_MOVE'

export {
  FETH_GRID_FAILURE,
  FETH_GRID_REQUEST,
  ON_MOVE_TO_LEFT,
  ON_MOVE_TO_RIGHT,
  ON_MOVE,
  FETH_GRID_SUCCESS
}
